env:
  node: true
  es2020: true
extends:
  - eslint:recommended
  - plugin:import/recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2020
rules:
  #quotes: ["warn", "single"]
  no-console: "warn"
  consistent-return: "warn"
  no-trailing-spaces: "warn"
  no-whitespace-before-property: "warn"
  no-multiple-empty-lines: ["warn", { max: 1 }]
  import/no-extraneous-dependencies: "error"
