version: '3'
services:
  webhooks:
    build:
      context: ./  
      dockerfile: Dockerfile
    container_name: bbb-webhooks 
    restart: always
    environment:
      - NODE_CONFIG_DIR=/etc/bigbluebutton/bbb-webhooks.yml:/app/config
    ports:
      - "3005:3005"
      - "3004:3004"
    volumes:
      - /etc/bigbluebutton/:/etc/bigbluebutton/
      - /var/log/bbb-webhooks/:/var/log/bbb-webhooks/
    network_mode: bridge
