bbb:
  serverDomain: SERVER_DOMAIN
  sharedSecret: SHARED_SECRET
  auth2_0: BEARER_AUTH
  includeEvents:
    __name: INCLUDE_EVENTS
    __format: json
  excludeEvents:
    __name: EXCLUDE_EVENTS
    __format: json
hooks:
  permanentURLs:
    __name: PERMANENT_HOOKS
    __format: json
  requestTimeout:
    __name: REQUEST_TIMEOUT
    __format: json
redis:
  host: REDIS_HOST
  port: REDIS_PORT
server:
  bind: SERVER_BIND_IP
  port: SERVER_PORT
