name: Build and push to registry
on:
  push:
permissions:
  contents: read
jobs:
  main:
    name: Build and push
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URI }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ vars.REGISTRY_URI }}/${{ vars.REGISTRY_ORGANIZATION }}/bbb-webhooks:${{ github.ref_name }}
          context: .
          cache-from: |
            type=registry,ref=${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_ORGANIZATION }}/bbb-webhooks:${{ github.ref_name }}
          cache-to: |
            type=registry,ref=${{ vars.REGISTRY_DOMAIN }}/${{ vars.REGISTRY_ORGANIZATION }}/bbb-webhooks:${{ github.ref_name }},mode=max,image-manifest=true
